name: 🦋 Changesets Release

on:
  push:
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: 🦋 Changesets Release
    runs-on: ubuntu-latest

    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write

    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: 🟧 Setup pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0

      - name: ⎔ Setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: 📥 Install dependencies
        run: pnpm install

      - name: 🚀 PR / Publish
        uses: changesets/action@e0538e686673de0265c8a3e2904b8c76beaa43fd # v1.5.2
        with:
          version: pnpm run changeset:version
          commit: "chore: Update version for release"
          title: "chore: Update version for release"
          publish: pnpm run changeset:release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
